# Generated by Django 5.2.7 on 2025-12-05 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', help_text="Category of metric (e.g., 'controller', 'anonymized', 'system')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metric_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('metrics_collected', models.IntegerField(default=0)),
                ('collectors_run', models.JSONField(default=list, help_text="List of collector names that were run (e.g., ['config', 'job_host_summary'])")),
                ('parameters_used', models.JSONField(default=dict, help_text='Parameters passed to the collection task (database, since, until, etc.)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if collection failed')),
            ],
            options={
                'db_table': 'collection_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at', 'status'], name='collection__started_aaf2fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('controller', 'Automation Controller'), ('host', 'Host'), ('service', 'Service'), ('cluster', 'Cluster'), ('other', 'Other')], db_index=True, default='controller', max_length=50)),
                ('source_id', models.CharField(help_text='Unique identifier for the source (e.g., UUID, hostname)', max_length=255)),
                ('source_name', models.CharField(blank=True, help_text='Human-readable name for the source', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the source')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'metric_sources',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='metric_sour_source__661193_idx')],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data', models.JSONField(help_text='The actual metrics data collected (structure varies by metric_type)')),
                ('data_size_bytes', models.IntegerField(default=0, help_text='Size of the data field in bytes (for monitoring storage)')),
                ('collection_duration_ms', models.IntegerField(blank=True, help_text='How long the collection took in milliseconds', null=True)),
                ('was_successful', models.BooleanField(default=True, help_text='Whether the collection was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if collection failed')),
                ('collection_run', models.ForeignKey(help_text='The collection run this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metrics_storage.collectionrun')),
                ('metric_type', models.ForeignKey(help_text='Type of collector that produced this metric', on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='metrics_storage.metrictype')),
            ],
            options={
                'db_table': 'metric_data',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['-collected_at', 'metric_type'], name='metric_data_collect_7404e1_idx'), models.Index(fields=['collection_run', 'metric_type'], name='metric_data_collect_6c43a5_idx'), models.Index(fields=['was_successful'], name='metric_data_was_suc_6d0308_idx')],
            },
        ),
    ]
