apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-service
  labels:
    app: my-service
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'configmaps', 'secrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'watch']
