apiVersion: v1
kind: Secret
metadata:
  name: my-service-secrets
type: Opaque
stringData:
  secret-key: 'dev-secret-key-change-in-production'
---
apiVersion: v1
kind: Secret
metadata:
  name: my-service-db
type: Opaque
stringData:
  username: 'my_service'
  password: 'my_service'
