# Generated by Django 5.2.7 on 2026-03-12 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("name", models.CharField(help_text="The name of this resource.", max_length=512)),
                ("started_at", models.DateTimeField(blank=True, help_text="When the process started", null=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="When the process completed", null=True)),
                ("error_message", models.TextField(blank=True, help_text="Error message if process failed")),
                ("description", models.TextField(blank=True, default="", help_text="Task description")),
                (
                    "function_name",
                    models.CharField(
                        help_text="Name of the function to execute (must match TASK_FUNCTIONS)", max_length=255
                    ),
                ),
                ("task_data", models.JSONField(default=dict, help_text="JSON data to pass to the task function")),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task should be executed (null for immediate execution)",
                        null=True,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for recurring tasks (e.g., '0 2 * * *')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_system_task",
                    models.BooleanField(
                        default=False, help_text="Whether this is a system-defined task that cannot be easily deleted"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, help_text="Number of execution attempts")),
                ("max_attempts", models.PositiveIntegerField(default=3, help_text="Maximum number of retry attempts")),
                ("timeout_seconds", models.PositiveIntegerField(default=3600, help_text="Task timeout in seconds")),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, help_text="JSON result data from task execution"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "permissions": [("can_execute_task", "Can execute task")],
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "worker_id",
                    models.CharField(
                        blank=True, help_text="ID of the worker that executed the task", max_length=100, null=True
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, help_text="JSON result data from this execution"),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if execution failed")),
                (
                    "execution_time_seconds",
                    models.FloatField(blank=True, help_text="Time taken to execute the task in seconds", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="The task that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetricsSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                (
                    "summary_date",
                    models.DateField(db_index=True, help_text="Date this summary covers (YYYY-MM-DD)", unique=True),
                ),
                (
                    "aggregated_metrics",
                    models.JSONField(default=dict, help_text="Aggregated metrics for the day (sums, averages, counts)"),
                ),
                (
                    "hourly_collection_ids",
                    models.JSONField(
                        default=dict, help_text="Map of collector_type -> list of HourlyMetricsCollection IDs"
                    ),
                ),
                ("config_data", models.JSONField(default=dict, help_text="Configuration data collected once per day")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("aggregated", "Aggregated"),
                            ("anonymized", "Anonymized"),
                            ("sent", "Sent to Segment"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "hourly_collections_count",
                    models.IntegerField(default=0, help_text="Total number of hourly collections included"),
                ),
                (
                    "missing_hours",
                    models.JSONField(default=list, help_text="List of hours that were missing collections"),
                ),
                (
                    "aggregation_completed_at",
                    models.DateTimeField(blank=True, help_text="When aggregation was completed", null=True),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if aggregation failed")),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollup_task_execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="TaskExecution that created this summary",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_summaries",
                        to="tasks.taskexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Metrics Summary",
                "verbose_name_plural": "Daily Metrics Summaries",
                "ordering": ["-summary_date"],
            },
        ),
        migrations.CreateModel(
            name="AnonymizedMetricsPayload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("summary_date", models.DateField(db_index=True, help_text="Date this payload covers")),
                ("anonymized_data", models.JSONField(help_text="Anonymized metrics payload ready for Segment")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retry", "Retry"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0, help_text="Number of send attempts")),
                ("max_retries", models.PositiveIntegerField(default=3, help_text="Maximum number of retry attempts")),
                (
                    "segment_event_name",
                    models.CharField(default="daily_metrics_rollup", help_text="Segment event name", max_length=255),
                ),
                ("segment_user_id", models.CharField(blank=True, help_text="Segment user ID", max_length=255)),
                (
                    "segment_message_id",
                    models.CharField(blank=True, help_text="Segment message ID for tracking", max_length=255),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, help_text="When payload was successfully sent", null=True),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if send failed")),
                ("payload_size_bytes", models.BigIntegerField(default=0, help_text="Size of anonymized_data in bytes")),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "daily_summary",
                    models.ForeignKey(
                        blank=True,
                        help_text="DailyMetricsSummary used to create this payload",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymized_payloads",
                        to="tasks.dailymetricssummary",
                    ),
                ),
                (
                    "anonymization_task_execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="TaskExecution that created this payload",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymized_payloads",
                        to="tasks.taskexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymized Metrics Payload",
                "verbose_name_plural": "Anonymized Metrics Payloads",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="HourlyMetricsCollection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                (
                    "collector_type",
                    models.CharField(
                        choices=[
                            ("job_host_summary_service", "Job Host Summary Service"),
                            ("unified_jobs", "Unified Jobs"),
                            ("credentials_service", "Credentials Service"),
                            ("main_jobevent_service", "Job Events (Event Modules)"),
                            ("execution_environments", "Execution Environments"),
                            ("controller_version_service", "Controller Version Service"),
                            ("table_metadata", "Table Metadata"),
                            ("config", "Configuration"),
                        ],
                        help_text="Type of metrics collector",
                        max_length=50,
                    ),
                ),
                (
                    "collection_timestamp",
                    models.DateTimeField(db_index=True, help_text="When this collection occurred (rounded to hour)"),
                ),
                ("raw_data", models.JSONField(default=dict, help_text="Raw metrics data from collector")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collected", "Collected"),
                            ("failed", "Failed"),
                            ("processed", "Processed"),
                        ],
                        default="collected",
                        max_length=20,
                    ),
                ),
                (
                    "collection_parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used for collection (database, since, until, etc.)"
                    ),
                ),
                ("data_size_bytes", models.BigIntegerField(default=0, help_text="Size of raw_data in bytes")),
                ("error_message", models.TextField(blank=True, help_text="Error message if collection failed")),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="TaskExecution that created this collection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hourly_collections",
                        to="tasks.taskexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hourly Metrics Collection",
                "verbose_name_plural": "Hourly Metrics Collections",
                "ordering": ["-collection_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["collector_type", "collection_timestamp"], name="tasks_hourl_collect_7ced30_idx"
                    ),
                    models.Index(fields=["collection_timestamp"], name="tasks_hourl_collect_1db2f8_idx"),
                    models.Index(fields=["status"], name="tasks_hourl_status_beccc2_idx"),
                ],
                "unique_together": {("collector_type", "collection_timestamp")},
            },
        ),
        migrations.AddIndex(
            model_name="dailymetricssummary",
            index=models.Index(fields=["summary_date"], name="tasks_daily_summary_41c800_idx"),
        ),
        migrations.AddIndex(
            model_name="dailymetricssummary",
            index=models.Index(fields=["status"], name="tasks_daily_status_f8be75_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailymetricssummary",
            unique_together={("summary_date",)},
        ),
        migrations.AddIndex(
            model_name="anonymizedmetricspayload",
            index=models.Index(fields=["status", "created"], name="tasks_anony_status_61cc36_idx"),
        ),
        migrations.AddIndex(
            model_name="anonymizedmetricspayload",
            index=models.Index(fields=["summary_date"], name="tasks_anony_summary_7c154e_idx"),
        ),
        migrations.AddConstraint(
            model_name="anonymizedmetricspayload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "sending", "sent"])),
                fields=("daily_summary",),
                name="unique_active_payload_per_summary",
            ),
        ),
    ]
