# Generated by Django 4.2.21 on 2025-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_system_task",
            field=models.BooleanField(
                default=False, help_text="Whether this is a system-defined task that cannot be easily deleted"
            ),
        ),
    ]
