# Generated by Django 5.2.7 on 2026-04-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymizedmetricspayload",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("unavailable", "Unavailable"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("retry", "Retry"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
