# Generated by Django 5.2.7 on 2026-02-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_is_recurring_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="taskchainmembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taskchainmembership",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskchainmembership",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="taskchainmembership",
            name="task",
        ),
        migrations.DeleteModel(
            name="TaskChain",
        ),
        migrations.DeleteModel(
            name="TaskChainMembership",
        ),
    ]
