# Generated by Django 5.2.7 on 2026-04-09 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_anonymizedmetricspayload_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="anonymizedmetricspayload",
            name="unique_active_payload_per_summary",
        ),
        migrations.AddConstraint(
            model_name="anonymizedmetricspayload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "sending", "sent", "unavailable"])),
                fields=("daily_summary",),
                name="unique_active_payload_per_summary",
            ),
        ),
    ]
