# Generated by Django 4.2.21 on 2025-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_add_system_task_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Task description"),
        ),
    ]
