# Generated by Django 5.2.7 on 2025-12-22 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_dailymetricssummary_anonymizedmetricspayload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anonymizedmetricspayload',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'sending', 'sent'])), fields=('daily_summary',), name='unique_active_payload_per_summary'),
        ),
    ]
