# Generated by Django 5.2.7 on 2026-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_anonymizedmetricspayload_unique_active_payload_per_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="max_attempts",
            field=models.PositiveIntegerField(default=7, help_text="Maximum number of retry attempts"),
        ),
    ]
