# Generated by Debuggernaut for AAP-75689

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_task_timeout_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Idempotency key supplied by the caller to prevent duplicate retry executions",
                max_length=255,
                null=True,
            ),
        ),
    ]
