# Generated by Debuggernaut for AAP-75688

from django.db import migrations, models

# Snapshot collector types (stored at 23:00 UTC by the old implicit contract)
_SNAPSHOT_COLLECTOR_TYPES = {
    "execution_environments",
    "config",
    "controller_version_service",
    "feature_flags_service",
    "table_metadata",
}

# Daily time-range collector types (also stored at 23:00 UTC by the old implicit contract)
_DAILY_COLLECTOR_TYPES = {
    "task_executions_service",
}


def backfill_collection_window(apps, schema_editor):
    """
    Backfill collection_window for pre-existing rows.

    Before AAP-75688, snapshot and daily collectors stored records at 23:00 UTC
    (the 'timestamp trick') so the daily rollup query window would pick them up.
    These records now need collection_window set explicitly.

    Hourly records stored at any other hour retain the default 'hourly' value.
    """
    HourlyMetricsCollection = apps.get_model("tasks", "HourlyMetricsCollection")

    # Backfill snapshot collectors: rows at hour=23 for known snapshot types
    HourlyMetricsCollection.objects.filter(
        collector_type__in=_SNAPSHOT_COLLECTOR_TYPES,
        collection_timestamp__hour=23,
    ).update(collection_window="snapshot")

    # Backfill daily collectors: rows at hour=23 for known daily types
    HourlyMetricsCollection.objects.filter(
        collector_type__in=_DAILY_COLLECTOR_TYPES,
        collection_timestamp__hour=23,
    ).update(collection_window="daily")


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_task_timeout_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="hourlymetricscollection",
            name="collection_window",
            field=models.CharField(
                choices=[("hourly", "Hourly"), ("snapshot", "Snapshot"), ("daily", "Daily")],
                default="hourly",
                help_text="Type of collection window: hourly (time-series), snapshot (point-in-time), or daily (full-day range)",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_collection_window, migrations.RunPython.noop),
    ]
