# Generated by Django 5.2.17 on 2026-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetricssummary',
            name='analytics_usage_snapshot',
            field=models.JSONField(default=dict, help_text='Private cumulative Prometheus snapshot used to derive usage deltas; this baseline is not included in anonymized payloads.'),
        ),
    ]
