# Generated by Django 5.2.7 on 2026-02-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_priority_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymizedmetricspayload",
            name="daily_summary",
            field=models.ForeignKey(
                blank=True,
                help_text="DailyMetricsSummary used to create this payload",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anonymized_payloads",
                to="tasks.dailymetricssummary",
            ),
        ),
    ]
