# Generated by Django 5.2.7 on 2026-02-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_hourlymetricscollection_collector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlymetricscollection',
            name='collector_type',
            field=models.CharField(choices=[('job_host_summary_service', 'Job Host Summary Service'), ('unified_jobs', 'Unified Jobs'), ('credentials_service', 'Credentials Service'), ('main_jobevent_service', 'Job Events (Event Modules)'), ('execution_environments', 'Execution Environments'), ('config', 'Configuration')], help_text='Type of metrics collector', max_length=50),
        ),
    ]
