# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 577af49
_src_path: /Volumes/case-sensitive-volume/projects/src/github.com/TheRealHaoLiu/platform-service-framework
app_name: ''
apps:
- core
- api
- tasks
- dashboard
project_name: metrics_service
src_branch: main
template: templates/project
