# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: https://github.com/ansible/platform-service-framework.git
_commit: b86a073e0d85f90c11e2264ba12a613d64d76432
project_name: metrics_service
template: templates/project
src_branch: main
apps:
  - core
  - dynamic_settings
  - tasks
  - dashboard
app_name: ""
