# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: f42e0f8
_src_path: https://github.com/ansible/platform-service-framework.git
app_name: ''
apps:
- core
- dynamic_settings
- tasks
- dashboard
project_name: metrics_service
src_branch: devel
template: templates/project
