# Dockerfile - Konflux/AppStudio compliant build
# Builds all Python dependencies from source for SBOM compliance

FROM registry.access.redhat.com/ubi9/python-312:latest

# Set working directory
WORKDIR /app

# Set environment variables for build and runtime
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 


# Install system dependencies required for building Python packages from source
# These include compilers and development headers for:
# - cryptography (requires Rust, OpenSSL headers)
# - psycopg/psycopg2 (requires PostgreSQL headers)
# - python-ldap (requires OpenLDAP headers)
# - cffi (requires libffi headers)
USER root
RUN dnf update -y && \
    dnf install -y \
        # C compiler and build tools
        gcc \
        gcc-c++ \
        make \
        # Python development headers
        python3.12-devel \
        # PostgreSQL development headers (for psycopg/psycopg2)
        postgresql-devel \
        libpq-devel \
        # OpenLDAP development headers (for python-ldap)
        openldap-devel \
        # OpenSSL development headers (for cryptography)
        openssl-devel \
        # libffi development headers (for cffi)
        libffi-devel \
        # Rust toolchain (required for cryptography package)
        rust \
        cargo \
        # Additional build dependencies
        redhat-rpm-config \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Create app directory and set permissions
RUN mkdir -p /app && chown -R 1001:1001 /app

# Copy the application code
COPY --chown=1001:1001 . /app/

# Switch to non-root user for build
USER 1001

# Set up cachi2 environment for hermetic builds (if available)
# This sources the environment file generated by the prefetch-dependencies task
RUN if [ -f /cachi2/cachi2.env ]; then \
        source /cachi2/cachi2.env; \
    fi && \
    pip install --no-cache-dir -r requirements-build.txt

# Copy and set up entrypoint script
USER root
COPY --chown=1001:1001 scripts/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Create necessary directories and files with proper permissions
RUN mkdir -p /app/logs /app/static && \
    chown -R 1001:1001 /app
USER 1001

# Expose port
EXPOSE 8000

# Set entrypoint and default command
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["python", "manage.py", "metrics_service", "run", "--host", "0.0.0.0", "--port", "8000"]

LABEL com.redhat.component="metrics-service" \
    name="metrics-service" \
    version="1.0.0" \
    summary="Metrics Service" \
    description="Backend utility for Ansible Automation Platform" \
    cpe="cpe:/a:redhat:metrics-service:1.0::rhel9" \
    org.opencontainers.image.created="${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}"
