# Generated by Django 5.2.7 on 2026-08-06 10:58

import apps.service_ingest.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("aap-mcp-server", "AAP MCP Server"),
                            ("aap-eda-server", "Event-Driven Ansible"),
                            ("aap-gateway", "AAP Gateway"),
                            ("aap-hub", "Automation Hub"),
                            ("ansible-lightspeed", "Ansible Lightspeed"),
                        ],
                        help_text="Machine identifier matching the service's gateway identity.",
                        max_length=128,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("mcp_tool_called", "MCP Tool Called"),
                            ("mcp_server_status", "MCP Server Heartbeat"),
                            ("eda_activation_daily_summary", "EDA Daily Activation Summary"),
                            ("eda_rule_firing_hourly", "EDA Rule Firing Stats"),
                            ("gateway_platform_snapshot", "Gateway Platform Snapshot"),
                            ("hub_content_usage_daily", "Hub Content Usage Daily"),
                        ],
                        help_text="Logical event type within the service (one service may have several).",
                        max_length=128,
                    ),
                ),
                ("display_name", models.CharField(max_length=256)),
                ("version", models.CharField(help_text="Schema version declared by the service.", max_length=64)),
                (
                    "segment_event_name",
                    models.CharField(
                        help_text="Event name emitted to Segment/Amplitude (human-readable, stable).", max_length=256
                    ),
                ),
                (
                    "payload_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON Schema describing the payload object. Stored for documentation; auto-generates rollup_config.",
                    ),
                ),
                (
                    "rollup_config",
                    models.JSONField(
                        default=dict,
                        help_text="Auto-inferred aggregation strategy (infer_rollup_config). Can be overridden in the registration payload.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "service_ingest_definition",
                "ordering": ["service_name", "event_name"],
                "unique_together": {("service_name", "event_name")},
            },
        ),
        migrations.CreateModel(
            name="ExternalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("payload_type", models.CharField(choices=[("batch", "Batch"), ("event", "Event")], max_length=10)),
                ("collection_start", models.DateTimeField(blank=True, null=True)),
                ("collection_end", models.DateTimeField(blank=True, null=True)),
                ("event_timestamp", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "segment_anonymous_id",
                    models.CharField(default=apps.service_ingest.models._uuid4_str, max_length=64),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The registered service that sent this payload.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="service_ingest.servicedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["service", "status"], name="si_event_svc_status_idx"),
                    models.Index(fields=["payload_type", "status", "created"], name="si_event_type_status_idx"),
                ],
            },
        ),
    ]
