# Generated by Django 5.2.7 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicedefinition",
            name="validate_payload",
            field=models.BooleanField(
                default=False,
                help_text="When True, inbound payloads are validated against payload_schema. When False, schema is stored for documentation only.",
            ),
        ),
    ]
