# Generated by Django 5.2.7 on 2025-12-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                (
                    "setting_key",
                    models.CharField(
                        help_text="The name of the setting that was changed (e.g., 'DEBUG', 'SECRET_KEY')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "previous_value",
                    models.TextField(
                        blank=True,
                        help_text="The previous value of the setting (JSON serialized). May be redacted for sensitive settings.",
                        null=True,
                    ),
                ),
                (
                    "current_value",
                    models.TextField(
                        blank=True,
                        help_text="The new value of the setting (JSON serialized). May be redacted for sensitive settings.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made this configuration change. Null if changed via system process.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified"],
                "indexes": [
                    models.Index(fields=["setting_key", "-modified"], name="dynamic_set_setting_e0a51d_idx"),
                    models.Index(fields=["last_modified_by", "-modified"], name="dynamic_set_last_mo_ea5212_idx"),
                ],
            },
        ),
    ]
