"""Authentication for the service ingest endpoint.

Accepts two mechanisms — whichever the calling service implements:

Option B — X-DAB-JW-TOKEN (preferred for production)
    Gateway-issued JWT signed with the gateway RSA private key.
    Validated by DAB's JWTCommonAuth using ANSIBLE_BASE_JWT_KEY.
    Services obtain this via POST /api/gateway/v1/workload_identity_tokens/.

Option A — X-ANSIBLE-SERVICE-AUTH (simpler for POC / installer wiring)
    Short-lived JWT signed with the shared RESOURCE_SERVER["SECRET_KEY"] (HS256),
    generated by DAB's get_service_token(). The same key that metrics-service
    already uses to call gateway. No gateway round-trip required.

Both options prove the caller is a legitimate AAP service. The actual
service_name is declared in the request body and validated against
ServiceDefinition — the JWT is an authenticity proof, not an identity claim.
"""

import logging

from rest_framework.authentication import BaseAuthentication
from rest_framework.exceptions import AuthenticationFailed

logger = logging.getLogger(__name__)


class ServiceUser:
    """Minimal user-like object for service-token-authenticated requests.

    Used only for Option A (X-ANSIBLE-SERVICE-AUTH). Option B returns a
    full DAB-synced DB user via JWTCommonAuth.
    """

    is_authenticated = True
    is_anonymous = False
    is_active = True
    is_staff = False
    is_superuser = False
    pk = None

    def __bool__(self) -> bool:
        return True

    def __str__(self) -> str:
        return "service:authenticated"


class IngestAuthentication(BaseAuthentication):
    """
    Tries X-DAB-JW-TOKEN (Option B) then X-ANSIBLE-SERVICE-AUTH (Option A).

    Returns None if neither header is present so other authenticators can run.
    Raises AuthenticationFailed if a header is present but the token is invalid.
    """

    def authenticate(self, request):
        if request.headers.get("X-DAB-JW-TOKEN"):
            return self._authenticate_dab_jwt(request)

        if request.headers.get("X-Ansible-Service-Auth"):
            return self._authenticate_service_token(request)

        return None

    def authenticate_header(self, request) -> str:
        return "X-DAB-JW-TOKEN, X-Ansible-Service-Auth"

    # ------------------------------------------------------------------
    # Option B — gateway RSA JWT (X-DAB-JW-TOKEN)
    # ------------------------------------------------------------------

    def _authenticate_dab_jwt(self, request):
        try:
            from ansible_base.jwt_consumer.common.auth import JWTCommonAuth

            jwt_auth = JWTCommonAuth()
            jwt_auth.parse_jwt_token(request)
        except Exception as exc:
            logger.debug("X-DAB-JW-TOKEN validation failed: %s", exc)
            raise AuthenticationFailed("Invalid or expired X-DAB-JW-TOKEN") from exc

        if jwt_auth.user is None:
            raise AuthenticationFailed("X-DAB-JW-TOKEN produced no user")

        logger.debug("Ingest: authenticated via X-DAB-JW-TOKEN (user=%s)", jwt_auth.user)
        return (jwt_auth.user, jwt_auth.token)

    # ------------------------------------------------------------------
    # Option A — shared-secret HS256 JWT (X-ANSIBLE-SERVICE-AUTH)
    # ------------------------------------------------------------------

    def _authenticate_service_token(self, request):
        import jwt as pyjwt
        from ansible_base.resource_registry.resource_server import get_resource_server_config

        token = request.headers.get("X-Ansible-Service-Auth", "").strip()
        if not token:
            return None

        try:
            config = get_resource_server_config()
            secret = config.get("SECRET_KEY")
            algorithm = config.get("JWT_ALGORITHM", "HS256")

            if not secret:
                logger.warning("RESOURCE_SERVER.SECRET_KEY not configured; rejecting X-Ansible-Service-Auth")
                raise AuthenticationFailed("Service token authentication is not configured")

            pyjwt.decode(token, secret, algorithms=[algorithm])
        except pyjwt.ExpiredSignatureError:
            raise AuthenticationFailed("X-Ansible-Service-Auth token has expired")
        except pyjwt.InvalidTokenError as exc:
            logger.debug("X-Ansible-Service-Auth validation failed: %s", exc)
            raise AuthenticationFailed("Invalid X-Ansible-Service-Auth token")

        logger.debug("Ingest: authenticated via X-Ansible-Service-Auth")
        return (ServiceUser(), token)
