# Generated by Django 5.2.17 on 2026-09-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_shared_user_content_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": [
                    ("member_organization", "User is member of this organization"),
                    (
                        "view_automation_dashboard",
                        "Can view organization automation dashboard data",
                    ),
                    (
                        "change_automation_dashboard",
                        "Can edit organization automation dashboard settings",
                    ),
                ]
            },
        ),
    ]
