# Generated by Django 4.2.23 on 2025-09-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_task_taskchain_taskexecution_taskchainmembership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskchain",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskchain",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="taskchain",
            name="tasks",
        ),
        migrations.AlterUniqueTogether(
            name="taskchainmembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taskchainmembership",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="taskchainmembership",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskchainmembership",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="taskchainmembership",
            name="task",
        ),
        migrations.AlterUniqueTogether(
            name="taskdependency",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="dependent_task",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="prerequisite_task",
        ),
        migrations.RemoveField(
            model_name="taskexecution",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskexecution",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="taskexecution",
            name="task",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskChain",
        ),
        migrations.DeleteModel(
            name="TaskChainMembership",
        ),
        migrations.DeleteModel(
            name="TaskDependency",
        ),
        migrations.DeleteModel(
            name="TaskExecution",
        ),
    ]
