# Generated by Django 4.2.23 on 2025-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_auditor",
            field=models.BooleanField(
                default=False, help_text="Designates that this user has read-only access to all resources."
            ),
        ),
    ]
