# Generated by Django 4.2.23 on 2025-09-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="task",
            name="started_at",
        ),
    ]
