# Generated by Django 4.2.21 on 2025-10-26 13:58

import apps.core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_configurationchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                (
                    "setting_key",
                    models.CharField(
                        help_text="The name of the setting that was changed (e.g., 'DEBUG', 'SECRET_KEY')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "previous_value",
                    models.TextField(
                        blank=True,
                        help_text="The previous value of the setting (JSON serialized). May be redacted for sensitive settings.",
                        null=True,
                    ),
                ),
                (
                    "current_value",
                    models.TextField(
                        blank=True,
                        help_text="The new value of the setting (JSON serialized). May be redacted for sensitive settings.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API Endpoint"),
                            ("management_command", "Management Command"),
                            ("reload", "Configuration Reload"),
                            ("system", "System Process"),
                        ],
                        help_text="The source of the configuration change",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the requester (if available)", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made this configuration change. Null if changed via system process.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified"],
                "permissions": [("manage_setting", "Can manage settings")],
            },
            bases=(models.Model, apps.core.mixins.AccessControlMixin),
        ),
        migrations.DeleteModel(
            name="ConfigurationChange",
        ),
        migrations.AddIndex(
            model_name="setting",
            index=models.Index(fields=["setting_key", "-modified"], name="core_settin_setting_69b439_idx"),
        ),
        migrations.AddIndex(
            model_name="setting",
            index=models.Index(fields=["last_modified_by", "-modified"], name="core_settin_last_mo_5b529e_idx"),
        ),
    ]
