# Generated by Django 4.2.21 on 2025-10-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_setting_delete_configurationchange_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setting",
            options={"ordering": ["-modified"]},
        ),
        migrations.RemoveField(
            model_name="setting",
            name="ip_address",
        ),
    ]
