# Generated by Django 5.2.7 on 2025-12-05 12:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user_type', models.CharField(default='normal', max_length=20)),
            ],
            options={
                'db_table': 'ar_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('source_database', models.CharField(default='awx', max_length=100)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('jobs_collected', models.IntegerField(default=0)),
                ('organizations_collected', models.IntegerField(default=0)),
                ('job_templates_collected', models.IntegerField(default=0)),
                ('hosts_collected', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ar_collection_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'ar_execution_environment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_container_group', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ar_instance_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ar_inventory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, help_text='ID from source AWX database', unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ar_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='automation_reports.inventory')),
            ],
            options={
                'db_table': 'ar_host',
                'ordering': ['name'],
                'unique_together': {('name', 'inventory')},
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='automation_reports.organization')),
            ],
            options={
                'db_table': 'ar_label',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_taken_manually_execute_minutes', models.BigIntegerField(default=60, help_text='Estimated time to execute this task manually (in minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('time_taken_create_automation_minutes', models.BigIntegerField(default=240, help_text='Estimated time to create the automation (in minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='automation_reports.organization')),
            ],
            options={
                'db_table': 'ar_job_template',
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='automation_reports.organization'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scm_type', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='automation_reports.organization')),
            ],
            options={
                'db_table': 'ar_project',
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(db_index=True, help_text='Job ID from source AWX database', unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('playbook_run', 'Playbook Run')], default='job', max_length=20)),
                ('job_type', models.CharField(choices=[('run', 'Run'), ('check', 'Check'), ('scan', 'Scan')], default='run', max_length=20)),
                ('launch_type', models.CharField(choices=[('manual', 'Manual'), ('relaunch', 'Relaunch'), ('callback', 'Callback'), ('scheduled', 'Scheduled'), ('dependency', 'Dependency'), ('workflow', 'Workflow'), ('webhook', 'Webhook'), ('sync', 'Sync'), ('scm', 'SCM Update')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('waiting', 'Waiting'), ('running', 'Running'), ('successful', 'Successful'), ('failed', 'Failed'), ('error', 'Error'), ('canceled', 'Canceled')], db_index=True, default='successful', max_length=25)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('elapsed', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('failed', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('num_hosts', models.IntegerField(default=0, help_text='Total hosts targeted')),
                ('changed_hosts_count', models.IntegerField(default=0)),
                ('dark_hosts_count', models.IntegerField(default=0)),
                ('failures_hosts_count', models.IntegerField(default=0)),
                ('ok_hosts_count', models.IntegerField(default=0)),
                ('processed_hosts_count', models.IntegerField(default=0)),
                ('skipped_hosts_count', models.IntegerField(default=0)),
                ('failed_hosts_count', models.IntegerField(default=0)),
                ('ignored_hosts_count', models.IntegerField(default=0)),
                ('rescued_hosts_count', models.IntegerField(default=0)),
                ('execution_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='automation_reports.executionenvironment')),
                ('instance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='automation_reports.instancegroup')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='automation_reports.inventory')),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_launched', to='automation_reports.aapuser')),
                ('job_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='automation_reports.jobtemplate')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='automation_reports.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='automation_reports.project')),
            ],
            options={
                'db_table': 'ar_job',
                'ordering': ['-finished'],
            },
        ),
        migrations.CreateModel(
            name='JobHostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('host_name', models.CharField(db_index=True, max_length=255)),
                ('changed', models.IntegerField(default=0)),
                ('dark', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('ignored', models.IntegerField(default=0)),
                ('rescued', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_summaries', to='automation_reports.host')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_summaries', to='automation_reports.job')),
            ],
            options={
                'db_table': 'ar_job_host_summary',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['job', 'host_name'], name='ar_job_host_job_id_5ba177_idx'), models.Index(fields=['host', 'created'], name='ar_job_host_host_id_80d4a3_idx')],
                'unique_together': {('job', 'host_name')},
            },
        ),
        migrations.CreateModel(
            name='JobLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='automation_reports.job')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='automation_reports.label')),
            ],
            options={
                'db_table': 'ar_job_label',
                'unique_together': {('job', 'label')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'finished'], name='ar_job_status_754e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_template', 'finished'], name='ar_job_job_tem_6f8488_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'finished'], name='ar_job_organiz_6d2ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['started'], name='ar_job_started_3ffd51_idx'),
        ),
    ]
