apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-service-config
data:
  METRICS_SERVICE_ENV: 'development'
  METRICS_SERVICE_DB_HOST: 'postgresql'
  METRICS_SERVICE_DB_PORT: '55432'
  METRICS_SERVICE_DB_NAME: 'metrics_service'
  metrics_service_REDIS_URL: 'redis://redis:6379/0'
  metrics_service_ALLOWED_HOSTS: 'localhost,127.0.0.1,metrics-service'
  metrics_service_CORS_ALLOWED_ORIGINS: 'http://localhost:3000,http://127.0.0.1:3000'
