apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  labels:
    app: metrics-service
    component: api
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 44926
      protocol: TCP
      name: http
  selector:
    app: metrics-service
    component: api
