# Generated by Django 5.2.7 on 2026-05-25 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0003_remove_anonymizedmetricspayload_unique_active_payload_per_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("collector_type", models.CharField(db_index=True, max_length=128)),
                (
                    "batch_type",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("backfill", "Backfill")],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("since", models.DateTimeField(blank=True, null=True)),
                ("until", models.DateTimeField(blank=True, null=True)),
                ("records_imported", models.PositiveIntegerField(default=0)),
                ("cursor", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_batches",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="StoredHostMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("hostname", models.CharField(db_index=True, max_length=512, unique=True)),
                ("host_id", models.IntegerField(default=0)),
                ("first_automation", models.DateTimeField(blank=True, null=True)),
                ("last_automation", models.DateTimeField(blank=True, null=True)),
                ("automated_counter", models.PositiveIntegerField(default=0)),
                ("deleted_counter", models.PositiveIntegerField(default=0)),
                ("last_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("ansible_product_serial", models.CharField(blank=True, max_length=255, null=True)),
                ("ansible_machine_id", models.CharField(blank=True, max_length=255, null=True)),
                ("ansible_host_variable", models.CharField(blank=True, max_length=512, null=True)),
                ("ansible_connection_variable", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "collection_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bi_connector.collectionbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoredIndirectAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                ("audit_id", models.IntegerField(db_index=True, unique=True)),
                ("host_id", models.IntegerField(blank=True, null=True)),
                ("job_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("organization_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "collection_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bi_connector.collectionbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoredJobHostSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("summary_id", models.IntegerField(db_index=True, unique=True)),
                ("host_id", models.IntegerField(blank=True, null=True)),
                ("job_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("host_name", models.CharField(blank=True, max_length=512, null=True)),
                ("organization_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("inventory_id", models.IntegerField(blank=True, null=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "collection_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bi_connector.collectionbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="collectionbatch",
            index=models.Index(fields=["status", "-created"], name="bi_connecto_status_dc9a3b_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionbatch",
            index=models.Index(fields=["collector_type", "-created"], name="bi_connecto_collect_e93e02_idx"),
        ),
        migrations.AddIndex(
            model_name="storedhostmetric",
            index=models.Index(fields=["last_automation"], name="bi_connecto_last_au_c90972_idx"),
        ),
        migrations.AddIndex(
            model_name="storedhostmetric",
            index=models.Index(fields=["first_automation"], name="bi_connecto_first_a_2fa86e_idx"),
        ),
        migrations.AddIndex(
            model_name="storedhostmetric",
            index=models.Index(fields=["deleted"], name="bi_connecto_deleted_982e22_idx"),
        ),
        migrations.AddIndex(
            model_name="storedindirectaudit",
            index=models.Index(fields=["created"], name="bi_connecto_created_7a892d_idx"),
        ),
        migrations.AddIndex(
            model_name="storedindirectaudit",
            index=models.Index(fields=["job_id"], name="bi_connecto_job_id_164f3d_idx"),
        ),
        migrations.AddIndex(
            model_name="storedjobhostsummary",
            index=models.Index(fields=["modified"], name="bi_connecto_modifie_3f93ea_idx"),
        ),
        migrations.AddIndex(
            model_name="storedjobhostsummary",
            index=models.Index(fields=["job_id"], name="bi_connecto_job_id_9ccabc_idx"),
        ),
        migrations.AddIndex(
            model_name="storedjobhostsummary",
            index=models.Index(fields=["organization_id"], name="bi_connecto_organiz_0931f0_idx"),
        ),
    ]
