#!/usr/bin/env python
"""
Run collection tasks for performance testing.

Executes hourly collection tasks that query AWX database tables and create
HourlyMetricsCollection records. Requires raw test data generated by
metrics-utility generators.

Prerequisites:
    - Raw AWX data (main_jobevent, main_host, main_jobhostsummary) must exist
    - Use metrics-utility fill_perf_db_data.py to populate test data

Dataset sizes:
- Small: ~100K events (20 jobs × 100 hosts × 50 tasks)
- Medium: ~1M events (20 jobs × 1000 hosts × 50 tasks)
- Large: ~10M events (200 jobs × 869 hosts × 50 tasks)

Usage:
    python tools/performance_tests/generate_test_data.py --size small
    python tools/performance_tests/generate_test_data.py --size medium
    python tools/performance_tests/generate_test_data.py --size large
    python tools/performance_tests/generate_test_data.py --size all
"""

import argparse
import json
import os
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

# Setup Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "metrics_service.settings")
import django  # noqa: E402

django.setup()

from perf_utils import PerformanceTimer, format_iso8601_timestamp, logger  # noqa: E402

from apps.tasks.models import DailyMetricsSummary, HourlyMetricsCollection  # noqa: E402
from apps.tasks.tasks_collector import (  # noqa: E402
    collect_host_metrics_hourly,
    collect_job_host_summary_hourly,
    collect_main_host_hourly,
)

# Data size configurations
# Note: These correspond to metrics-utility fill_perf_db_data.py configurations
DATASET_SIZES = {
    "small": {
        "target_events": 100_000,
        "description": "Small dataset (~100K events from 20 jobs × 100 hosts × 50 tasks)",
        "metrics_utility_config": {"jobs": 20, "hosts": 100, "tasks": 50},
    },
    "medium": {
        "target_events": 1_000_000,
        "description": "Medium dataset (~1M events from 20 jobs × 1000 hosts × 50 tasks)",
        "metrics_utility_config": {"jobs": 20, "hosts": 1000, "tasks": 50},
    },
    "large": {
        "target_events": 10_000_000,
        "description": "Large dataset (~10M events from 200 jobs × 869 hosts × 50 tasks)",
        "metrics_utility_config": {"jobs": 200, "hosts": 869, "tasks": 50},
    },
}


def run_collection_task(task_func, task_name: str, hour_timestamp: str) -> dict:
    """
    Run a single collection task for a specific hour.

    Args:
        task_func: Collection task function to run
        task_name: Name of the task (for logging)
        hour_timestamp: ISO timestamp for the hour to collect

    Returns:
        Task result dictionary
    """
    logger.debug(f"Running {task_name} for {hour_timestamp}")

    try:
        result = task_func(hour_timestamp=hour_timestamp, database="awx")
        if result.get("status") != "success":
            logger.warning(f"{task_name} returned status: {result.get('status')}")
        return result
    except Exception as e:
        logger.error(f"Error running {task_name}: {e}")
        return {"status": "error", "error": str(e)}


def run_hourly_collections(size_name: str, cleanup_existing: bool = True) -> dict:
    """
    Run hourly collection tasks for 24 hours.

    This executes the production collection tasks that query raw AWX database tables
    and create HourlyMetricsCollection records using metrics-utility collectors.

    Args:
        size_name: Dataset size name (small, medium, large)
        cleanup_existing: Whether to delete existing collections first

    Returns:
        Dictionary with collection statistics

    Raises:
        RuntimeError: If raw AWX data is not available
    """
    config = DATASET_SIZES[size_name]

    logger.info(f"Running collections for {config['description']}")
    logger.info(f"Target: {config['target_events']:,} events")
    logger.info(
        f"Expected metrics-utility config: {config['metrics_utility_config']['jobs']} jobs × "
        f"{config['metrics_utility_config']['hosts']} hosts × "
        f"{config['metrics_utility_config']['tasks']} tasks"
    )
    logger.info("\nNote: Raw AWX data must be generated first using metrics-utility generators")
    logger.info("See USAGE.md Prerequisites section for setup instructions\n")

    # Cleanup existing data if requested
    if cleanup_existing:
        logger.info("Cleaning up existing HourlyMetricsCollection data...")
        with PerformanceTimer("cleanup_existing_data"):
            deleted_hourly = HourlyMetricsCollection.objects.all().delete()[0]
            deleted_daily = DailyMetricsSummary.objects.all().delete()[0]
            logger.info(f"Deleted {deleted_hourly} hourly collections, {deleted_daily} daily summaries")

    # Run collection tasks for 24 hours
    base_timestamp = datetime.now(UTC).replace(minute=0, second=0, microsecond=0) - timedelta(days=1)

    collections_created = 0
    total_data_size = 0
    failed_collections = 0

    # Collection tasks to run (order matches production)
    collection_tasks = [
        (collect_job_host_summary_hourly, "collect_job_host_summary_hourly"),
        (collect_host_metrics_hourly, "collect_host_metrics_hourly"),
        (collect_main_host_hourly, "collect_main_host_hourly"),
    ]

    with PerformanceTimer(f"run_hourly_collections_{size_name}") as timer:
        for hour in range(24):
            hour_timestamp = (base_timestamp + timedelta(hours=hour)).isoformat()

            # Run each collection task for this hour
            for task_func, task_name in collection_tasks:
                result = run_collection_task(task_func, task_name, hour_timestamp)

                if result.get("status") == "success":
                    collections_created += 1
                    # Get the created collection to track size
                    if "record_id" in result:
                        try:
                            collection = HourlyMetricsCollection.objects.get(id=result["record_id"])
                            total_data_size += collection.data_size_bytes
                        except HourlyMetricsCollection.DoesNotExist:
                            pass
                else:
                    failed_collections += 1
                    logger.error(f"Failed: {task_name} for {hour_timestamp}")

            if (hour + 1) % 6 == 0:  # Log every 6 hours
                logger.info(
                    f"Completed {hour + 1}/24 hours ({collections_created}/72 collections, "
                    f"{total_data_size / 1024 / 1024:.2f} MB)"
                )

    stats = {
        "size_name": size_name,
        "target_events": config["target_events"],
        "collections_created": collections_created,
        "collections_failed": failed_collections,
        "total_data_size_bytes": total_data_size,
        "total_data_size_mb": total_data_size / 1024 / 1024,
        "duration_seconds": timer.metrics.duration_seconds,
        "memory_delta_mb": timer.metrics.memory_delta_mb,
    }

    logger.info(
        f"\nCollection tasks complete for {size_name}:\n"
        f"  Collections: {collections_created} ({failed_collections} failed)\n"
        f"  Total size: {stats['total_data_size_mb']:.2f} MB\n"
        f"  Duration: {stats['duration_seconds']:.2f}s\n"
        f"  Memory delta: {stats['memory_delta_mb']:+.2f} MB"
    )

    if failed_collections > 0:
        logger.warning(f"\n⚠️  {failed_collections} collections failed. This likely means raw AWX data is missing.")
        logger.warning("   Use metrics-utility generators to populate test data (see USAGE.md)")

    return stats


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Run hourly collection tasks for performance testing",
        epilog="Note: Requires raw AWX data generated by metrics-utility. See USAGE.md for setup.",
    )
    parser.add_argument(
        "--size",
        choices=["small", "medium", "large", "all"],
        required=True,
        help="Dataset size to collect (corresponds to metrics-utility generator config)",
    )
    parser.add_argument(
        "--keep-existing",
        action="store_true",
        help="Keep existing HourlyMetricsCollection data (don't cleanup before running)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output file for collection statistics (JSON)",
    )

    args = parser.parse_args()

    all_stats = []

    sizes = ["small", "medium", "large"] if args.size == "all" else [args.size]

    cleanup_existing = not args.keep_existing
    for size in sizes:
        stats = run_hourly_collections(size, cleanup_existing=cleanup_existing)
        all_stats.append(stats)
        # Only cleanup before first dataset
        cleanup_existing = False

    # Write statistics if output specified
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, "w") as f:
            json.dump(
                {
                    "generated_at": format_iso8601_timestamp(),
                    "datasets": all_stats,
                },
                f,
                indent=2,
            )
        logger.info(f"Statistics written to {args.output}")


if __name__ == "__main__":
    main()
