# Generated by Django 5.2.7 on 2026-04-09 19:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

# Help text constants — shared across all CommonModel-derived models in this app.
# Note: DAB's CommonModel uses the same string for both created and modified timestamp
# fields; _TIMESTAMP_HELP reflects that upstream text verbatim so the migration stays
# consistent with what Django detects from the model.
_TIMESTAMP_HELP = "The date/time this resource was created."
_CREATED_BY_HELP = "The user who created this resource."
_MODIFIED_BY_HELP = "The user who last modified this resource."

# Reusable FK kwargs for the audit trail fields added by CommonModel
_CREATED_BY_FK = {
    "default": None,
    "editable": False,
    "help_text": _CREATED_BY_HELP,
    "null": True,
    "on_delete": django.db.models.deletion.SET_NULL,
    "related_name": "%(app_label)s_%(class)s_created+",
    "to": settings.AUTH_USER_MODEL,
}
_MODIFIED_BY_FK = {
    "default": None,
    "editable": False,
    "help_text": _MODIFIED_BY_HELP,
    "null": True,
    "on_delete": django.db.models.deletion.SET_NULL,
    "related_name": "%(app_label)s_%(class)s_modified+",
    "to": settings.AUTH_USER_MODEL,
}


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text=_TIMESTAMP_HELP)),
                ("created", models.DateTimeField(auto_now_add=True, help_text=_TIMESTAMP_HELP)),
                (
                    "template_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="AWX job template ID (from AWX database main_jobtemplate table)",
                        unique=True,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(db_index=True, help_text="Template name for display (from AWX)", max_length=512),
                ),
                (
                    "time_taken_manually_execute_minutes",
                    models.BigIntegerField(
                        blank=True,
                        help_text="User override: Estimated time to perform this task manually (minutes)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "time_taken_create_automation_minutes",
                    models.BigIntegerField(
                        blank=True,
                        help_text="User override: Estimated time spent creating this automation (minutes)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_by", models.ForeignKey(**_CREATED_BY_FK)),
                ("modified_by", models.ForeignKey(**_MODIFIED_BY_FK)),
            ],
            options={
                "verbose_name": "Template Metadata",
                "verbose_name_plural": "Template Metadata",
                "db_table": "dashboard_template_metadata",
                "ordering": ["template_name"],
            },
        ),
        migrations.CreateModel(
            name="JobData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text=_TIMESTAMP_HELP)),
                ("created", models.DateTimeField(auto_now_add=True, help_text=_TIMESTAMP_HELP)),
                (
                    "job_id",
                    models.IntegerField(
                        db_index=True, help_text="AWX job ID (from AWX database main_unifiedjob table)", unique=True
                    ),
                ),
                ("template_name", models.CharField(help_text="Job template name (from AWX)", max_length=512)),
                ("template_id", models.IntegerField(blank=True, help_text="AWX template ID", null=True)),
                ("project_id", models.IntegerField(blank=True, help_text="AWX project ID", null=True)),
                (
                    "project_name",
                    models.CharField(
                        blank=True, help_text="Project name for display (from AWX)", max_length=512, null=True
                    ),
                ),
                ("organization_id", models.IntegerField(blank=True, help_text="AWX organization ID", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending"),
                            ("waiting", "Waiting"),
                            ("running", "Running"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="successful",
                        max_length=25,
                    ),
                ),
                (
                    "started",
                    models.DateTimeField(
                        default=None,
                        help_text="Job start timestamp (from AWX database main_unifiedjob table)",
                        null=True,
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        db_index=True,
                        default=None,
                        help_text="Job finish timestamp (from AWX database main_unifiedjob table)",
                        null=True,
                    ),
                ),
                (
                    "elapsed",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Job elapsed time in seconds (from AWX database main_unifiedjob table)",
                        max_digits=15,
                    ),
                ),
                (
                    "num_hosts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of hosts involved in the job (calculated from AWX job host summaries)",
                    ),
                ),
                (
                    "launched_by_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="AWX user ID of the user who launched the job (from AWX database main_unifiedjob table)",
                        null=True,
                    ),
                ),
                (
                    "launched_by_username",
                    models.CharField(
                        blank=True,
                        help_text="AWX username of the user who launched the job (from AWX database main_unifiedjob table)",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("awx_created", models.DateTimeField(blank=True, help_text="Creation timestamp from AWX", null=True)),
                ("awx_modified", models.DateTimeField(blank=True, help_text="Modification timestamp from AWX", null=True)),
                ("created_by", models.ForeignKey(**_CREATED_BY_FK)),
                ("modified_by", models.ForeignKey(**_MODIFIED_BY_FK)),
                (
                    "template_metadata",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to TemplateMetadata for this job's template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="dashboard_reports.templatemetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Data",
                "verbose_name_plural": "Jobs Data",
                "db_table": "dashboard_job_data",
                "ordering": ["-started"],
            },
        ),
        migrations.CreateModel(
            name="FilterSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text=_TIMESTAMP_HELP)),
                ("created", models.DateTimeField(auto_now_add=True, help_text=_TIMESTAMP_HELP)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text='Display name for this filter set (e.g. "Last 30 days")',
                        max_length=255,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        help_text="Filter configuration: {organizations: [], projects: [], labels: [], date_range: {}}"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's default filter set (only one allowed per user)",
                    ),
                ),
                ("created_by", models.ForeignKey(**_CREATED_BY_FK)),
                ("modified_by", models.ForeignKey(**_MODIFIED_BY_FK)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this filter set",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Filter Set",
                "verbose_name_plural": "Filter Sets",
                "db_table": "dashboard_filter_set",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["user", "is_default"], name="dashboard_fs_user_default_idx"),
                    models.Index(fields=["user", "-modified"], name="dashboard_fs_user_mod_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("user", "is_default"),
                        name="one_default_per_user",
                        violation_error_message="User can only have one default filter set",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobHostSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text=_TIMESTAMP_HELP)),
                ("created", models.DateTimeField(auto_now_add=True, help_text=_TIMESTAMP_HELP)),
                (
                    "host_summary_id",
                    models.IntegerField(
                        blank=True,
                        help_text="AWX host summary ID (from AWX database main_hostsummary table)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "host_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="AWX host ID (from AWX database main_host table)",
                        null=True,
                    ),
                ),
                (
                    "host_name",
                    models.CharField(db_index=True, help_text="Host name for display (from AWX)", max_length=512),
                ),
                ("created_by", models.ForeignKey(**_CREATED_BY_FK)),
                (
                    "job_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_summaries",
                        to="dashboard_reports.jobdata",
                    ),
                ),
                ("modified_by", models.ForeignKey(**_MODIFIED_BY_FK)),
            ],
            options={
                "verbose_name": "Job Data Host Summary",
                "verbose_name_plural": "Job Data Host Summaries",
                "db_table": "dashboard_job_data_host_summary",
                "indexes": [models.Index(fields=["job_data", "host_id"], name="dashboard_jhs_job_host_idx")],
            },
        ),
        migrations.CreateModel(
            name="JobLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text=_TIMESTAMP_HELP)),
                ("created", models.DateTimeField(auto_now_add=True, help_text=_TIMESTAMP_HELP)),
                ("label_id", models.IntegerField(blank=True, db_index=True, help_text="AWX label ID", null=True)),
                ("created_by", models.ForeignKey(**_CREATED_BY_FK)),
                (
                    "job_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="dashboard_reports.jobdata",
                    ),
                ),
                ("modified_by", models.ForeignKey(**_MODIFIED_BY_FK)),
            ],
            options={
                "verbose_name": "Job Data Label",
                "verbose_name_plural": "Job Data Labels",
                "db_table": "dashboard_job_data_label",
                "indexes": [models.Index(fields=["job_data", "label_id"], name="dashboard_jl_job_label_idx")],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text=_TIMESTAMP_HELP)),
                ("created", models.DateTimeField(auto_now_add=True, help_text=_TIMESTAMP_HELP)),
                (
                    "monthly_subscription_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription cost for AAP subscription",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "engineer_avg_hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average hourly rate for engineers performing manual tasks (used for cost calculations in reports)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "include_template_creation_time_in_costs",
                    models.BooleanField(
                        default=True,
                        help_text="Include template creation time in cost calculations. If false, costs related to template creation time will be excluded.",
                    ),
                ),
                ("created_by", models.ForeignKey(**_CREATED_BY_FK)),
                ("modified_by", models.ForeignKey(**_MODIFIED_BY_FK)),
            ],
            options={
                "verbose_name": "Subscription Cost",
                "verbose_name_plural": "Subscription Costs",
                "db_table": "dashboard_subscription_cost",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)), name="dashboard_subscription_cost_singleton_pk"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="jobdata",
            index=models.Index(fields=["template_id"], name="dashboard_jd_template_idx"),
        ),
        migrations.AddIndex(
            model_name="jobdata",
            index=models.Index(fields=["project_id"], name="dashboard_jd_project_idx"),
        ),
        migrations.AddIndex(
            model_name="jobdata",
            index=models.Index(fields=["organization_id"], name="dashboard_jd_organization_idx"),
        ),
    ]
