# Generated by Django 5.2.7 on 2026-06-23 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_reports", "0002_jobdata_organization_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AWXJobTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("template_id", models.IntegerField(db_index=True, help_text="AWX job template ID", unique=True)),
                ("name", models.CharField(db_index=True, help_text="Job template name (from AWX)", max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AWX Job Template Cache",
                "verbose_name_plural": "AWX Job Template Cache",
                "db_table": "dashboard_awx_job_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AWXLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("label_id", models.IntegerField(db_index=True, help_text="AWX label ID", unique=True)),
                ("name", models.CharField(db_index=True, help_text="Label name (from AWX)", max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AWX Label Cache",
                "verbose_name_plural": "AWX Label Cache",
                "db_table": "dashboard_awx_label",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AWXOrganization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("org_id", models.IntegerField(db_index=True, help_text="AWX organization ID", unique=True)),
                ("name", models.CharField(db_index=True, help_text="Organization name (from AWX)", max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AWX Organization Cache",
                "verbose_name_plural": "AWX Organization Cache",
                "db_table": "dashboard_awx_organization",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AWXProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("project_id", models.IntegerField(db_index=True, help_text="AWX project ID", unique=True)),
                ("name", models.CharField(db_index=True, help_text="Project name (from AWX)", max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AWX Project Cache",
                "verbose_name_plural": "AWX Project Cache",
                "db_table": "dashboard_awx_project",
                "ordering": ["name"],
            },
        ),
    ]
