"""
Core models for metrics_service.
For full AAP/DAB features, install with: pip install -e ".[dev]"
"""

from django.contrib.auth.models import AbstractUser
from django.db import models

# Basic models for immediate setup
# For full AAP features, replace with DAB abstract models when ready
try:
    from ansible_base.activitystream.models import AuditableModel
    from ansible_base.lib.abstract_models import (
        AbstractDABUser,
        AbstractOrganization,
        AbstractTeam,
        CommonModel,
        NamedCommonModel,
    )
    from ansible_base.lib.utils.models import user_summary_fields
    from ansible_base.rbac.permission_registry import permission_registry
    from ansible_base.resource_registry.fields import AnsibleResourceField

    DAB_AVAILABLE = True
except ImportError:
    # Provide simple alternatives for immediate setup
    DAB_AVAILABLE = False

    # Simple base classes when DAB is not available
    class CommonModel(models.Model):
        created = models.DateTimeField(auto_now_add=True)
        modified = models.DateTimeField(auto_now=True)

        class Meta:
            abstract = True

    class NamedCommonModel(CommonModel):
        name = models.CharField(max_length=512)
        description = models.TextField(blank=True, default="")

        class Meta:
            abstract = True

    class AuditableModel(models.Model):
        class Meta:
            abstract = True

    class AbstractDABUser(AbstractUser):
        class Meta:
            abstract = True

    class AbstractOrganization(NamedCommonModel):
        class Meta:
            abstract = True

    class AbstractTeam(NamedCommonModel):
        organization = models.ForeignKey("Organization", on_delete=models.CASCADE)

        class Meta:
            abstract = True


# Password handling functions - only available when DAB is enabled
if DAB_AVAILABLE:
    from django.contrib.auth.hashers import (
        UNUSABLE_PASSWORD_PREFIX,
        UNUSABLE_PASSWORD_SUFFIX_LENGTH,
        get_hashers_by_algorithm,
        identify_hasher,
        make_password,
    )

    def password_is_hashed(password):
        """
        Returns a boolean of whether password is hashed with loaded algorithms.
        """
        if password is None:
            return False
        try:
            hasher = identify_hasher(password)
        except ValueError:
            # hasher can't be identified or is not loaded
            return False
        return hasher.algorithm in get_hashers_by_algorithm().keys()

    def password_is_usable(password):
        """
        Returns True if password is None or wasn't generated by django.contrib.auth.hashers.make_password(None).
        """
        unusable_password_len = len(UNUSABLE_PASSWORD_PREFIX) + UNUSABLE_PASSWORD_SUFFIX_LENGTH

        return password is None or not (
            password.startswith(UNUSABLE_PASSWORD_PREFIX) and len(password) == unusable_password_len
        )


class Organization(AbstractOrganization):
    """
    Organization model.
    """

    class Meta:
        ordering = ["id"]
        permissions = [
            ("member_organization", "User is member of this organization"),
        ]

    if DAB_AVAILABLE:
        resource = AnsibleResourceField(primary_key_field="id")

    users = models.ManyToManyField(
        "User",
        related_name="member_of_organizations",
        blank=True,
        help_text="The list of users on this organization",
    )

    admins = models.ManyToManyField(
        "User",
        related_name="admin_of_organizations",
        blank=True,
        help_text="The list of admins for this organization",
    )

    # Example custom field - replace or remove as needed
    extra_field = models.CharField(max_length=100, null=True, blank=True)

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Fallback implementation when DAB is not fully available.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # For now, return all objects - in production this would implement proper RBAC
        # When DAB is fully configured, this method would be provided by the DAB base class
        return queryset

    def __str__(self):
        return self.name


class User(AbstractDABUser, CommonModel, AuditableModel):
    """
    Custom User model.
    """

    class Meta(AbstractDABUser.Meta):
        ordering = ["id"]

    # Override the groups and user_permissions to avoid conflicts with auth.User
    groups = models.ManyToManyField(
        "auth.Group",
        verbose_name="groups",
        blank=True,
        help_text="The groups this user belongs to.",
        related_name="core_user_set",
        related_query_name="core_user",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        verbose_name="user permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        related_name="core_user_set",
        related_query_name="core_user",
    )

    if DAB_AVAILABLE:
        resource = AnsibleResourceField(primary_key_field="id")
        activity_stream_excluded_field_names = ["last_login", "password"]

    def save(self, *args, **kwargs):
        """
        Override save to handle password hashing when DAB is available.
        """
        if DAB_AVAILABLE:
            if self.password == "":
                self.password = None

            if password_is_usable(self.password) and not password_is_hashed(self.password):
                self.password = make_password(self.password)
        super().save(*args, **kwargs)

    def summary_fields(self):
        """
        Return summary fields for this user.
        """
        if DAB_AVAILABLE:
            return user_summary_fields(self)
        return {}

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Fallback implementation when DAB is not fully available.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # For now, return all objects - in production this would implement proper RBAC
        # When DAB is fully configured, this method would be provided by the DAB base class
        return queryset

    def __str__(self):
        return self.username


class Team(AbstractTeam):
    """
    Team model.
    """

    class Meta:
        ordering = ["id"]
        abstract = False
        unique_together = [("organization", "name")]
        ordering = ("organization__name", "name")
        permissions = [("member_team", "Has all roles assigned to this team")]

    if DAB_AVAILABLE:
        resource = AnsibleResourceField(primary_key_field="id")

    team_parents = models.ManyToManyField(
        "Team",
        related_name="team_children",
        blank=True,
        help_text="Parent teams for hierarchy support",
    )

    users = models.ManyToManyField(
        User,
        related_name="teams",
        blank=True,
        help_text="The list of users on this team",
    )

    admins = models.ManyToManyField(
        User,
        related_name="teams_administered",
        blank=True,
        help_text="The list of admins for this team",
    )

    # Relations to ignore for certain operations
    ignore_relations = []

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Fallback implementation when DAB is not fully available.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # For now, return all objects - in production this would implement proper RBAC
        # When DAB is fully configured, this method would be provided by the DAB base class
        return queryset

    def __str__(self):
        return f"{self.organization.name} - {self.name}"


class Animal(NamedCommonModel, AuditableModel):
    """
    Example model to demonstrate AAP patterns.
    Replace with your actual business models.
    """

    class Meta:
        ordering = ["id"]
        permissions = [("can_pet", "Can pet animal")]

    # Exclude sensitive fields from activity stream
    activity_stream_excluded_field_names = ["age"]

    ANIMAL_KINDS = (
        ("dog", "Dog"),
        ("cat", "Cat"),
        ("bird", "Bird"),
        ("fish", "Fish"),
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="The owner of this animal",
    )

    kind = models.CharField(
        max_length=4,
        choices=ANIMAL_KINDS,
        default="dog",
        help_text="The type of animal",
    )

    age = models.PositiveIntegerField(null=True, default=1, help_text="Age of the animal in years")

    people_friends = models.ManyToManyField(
        User,
        related_name="animal_friends",
        blank=True,
        help_text="People who are friends with this animal",
    )

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Fallback implementation when DAB is not fully available.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # For now, return all objects - in production this would implement proper RBAC
        # When DAB is fully configured, this method would be provided by the DAB base class
        return queryset

    def __str__(self):
        return f"{self.name} ({self.get_kind_display()})"


class Task(NamedCommonModel, AuditableModel):
    """
    Database model for scheduled tasks.
    """

    class Meta:
        ordering = ["id"]
        permissions = [("can_execute_task", "Can execute task")]

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("running", "Running"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("cancelled", "Cancelled"),
        ("waiting_for_dependencies", "Waiting for Dependencies"),
    ]

    PRIORITY_CHOICES = [
        (1, "Low"),
        (2, "Normal"),
        (3, "High"),
        (4, "Critical"),
    ]

    # Task identification and metadata
    function_name = models.CharField(
        max_length=255, help_text="Name of the function to execute (must match TASK_FUNCTIONS)"
    )

    task_data = models.JSONField(default=dict, help_text="JSON data to pass to the task function")

    # Scheduling information
    scheduled_time = models.DateTimeField(
        null=True, blank=True, help_text="When the task should be executed (null for immediate execution)"
    )

    cron_expression = models.CharField(
        max_length=100, null=True, blank=True, help_text="Cron expression for recurring tasks (e.g., '0 2 * * *')"
    )

    is_recurring = models.BooleanField(
        default=False, help_text="Whether this task should repeat based on cron_expression"
    )

    # Execution tracking
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default="pending")

    priority = models.IntegerField(
        choices=PRIORITY_CHOICES, default=2, help_text="Task priority (higher numbers = higher priority)"
    )

    attempts = models.PositiveIntegerField(default=0, help_text="Number of execution attempts")

    max_attempts = models.PositiveIntegerField(default=3, help_text="Maximum number of retry attempts")

    timeout_seconds = models.PositiveIntegerField(default=3600, help_text="Task timeout in seconds")

    # Execution results
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    result_data = models.JSONField(default=dict, blank=True, help_text="JSON result data from task execution")

    error_message = models.TextField(blank=True, help_text="Error message if task failed")

    # Ownership and organization
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_tasks",
        help_text="User who created this task",
    )

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Fallback implementation when DAB is not fully available.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # For now, return all objects - in production this would implement proper RBAC
        # When DAB is fully configured, this method would be provided by the DAB base class
        return queryset

    def __str__(self):
        return f"{self.name} ({self.function_name}) - {self.get_status_display()}"

    def is_ready_to_run(self):
        """Check if task is ready to be executed."""
        from django.utils import timezone

        if self.status != "pending":
            return False

        # Check if dependencies are completed
        if self.dependencies.filter(
            prerequisite_task__status__in=["pending", "running", "waiting_for_dependencies"]
        ).exists():
            return False

        # Check if scheduled time has passed
        if self.scheduled_time and self.scheduled_time > timezone.now():
            return False

        return True

    def can_retry(self):
        """Check if task can be retried."""
        return self.attempts < self.max_attempts and self.status == "failed"

    def get_next_run_time(self):
        """Calculate next run time for recurring tasks."""
        if not self.is_recurring or not self.cron_expression:
            return None

        try:
            from datetime import datetime

            from croniter import croniter
            from django.utils import timezone

            cron = croniter(self.cron_expression, timezone.now())
            return cron.get_next(datetime)
        except ImportError:
            # croniter not available, return None
            return None
        except Exception:
            # Invalid cron expression
            return None


class TaskDependency(CommonModel):
    """
    Model to define task dependencies for chaining.
    """

    class Meta:
        unique_together = ["dependent_task", "prerequisite_task"]
        verbose_name_plural = "Task Dependencies"

    dependent_task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name="dependencies", help_text="Task that depends on another task"
    )

    prerequisite_task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name="dependents",
        help_text="Task that must complete before dependent_task can run",
    )

    required_status = models.CharField(
        max_length=30,
        choices=Task.STATUS_CHOICES,
        default="completed",
        help_text="Required status of prerequisite task",
    )

    def __str__(self):
        return f"{self.dependent_task.name} depends on {self.prerequisite_task.name}"


class TaskExecution(CommonModel, AuditableModel):
    """
    Model to track individual task executions for history and debugging.
    """

    class Meta:
        ordering = ["-started_at"]

    task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name="executions", help_text="The task that was executed"
    )

    status = models.CharField(max_length=30, choices=Task.STATUS_CHOICES)

    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    worker_id = models.CharField(
        max_length=100, null=True, blank=True, help_text="ID of the worker that executed the task"
    )

    result_data = models.JSONField(default=dict, blank=True, help_text="JSON result data from this execution")

    error_message = models.TextField(blank=True, help_text="Error message if execution failed")

    execution_time_seconds = models.FloatField(
        null=True, blank=True, help_text="Time taken to execute the task in seconds"
    )

    def __str__(self):
        return f"{self.task.name} execution at {self.started_at}"

    def save(self, *args, **kwargs):
        # Calculate execution time if completed
        if self.completed_at and self.started_at:
            self.execution_time_seconds = (self.completed_at - self.started_at).total_seconds()
        super().save(*args, **kwargs)


class TaskChain(NamedCommonModel, AuditableModel):
    """
    Model to define named task chains for complex workflows.
    """

    class Meta:
        ordering = ["id"]

    tasks = models.ManyToManyField(
        Task, through="TaskChainMembership", related_name="chains", help_text="Tasks in this chain"
    )

    is_active = models.BooleanField(default=True, help_text="Whether this chain is active")

    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="created_chains"
    )

    def __str__(self):
        return self.name


class TaskChainMembership(CommonModel):
    """
    Through model for TaskChain to Task relationship with ordering.
    """

    class Meta:
        unique_together = ["chain", "task"]
        ordering = ["order"]

    chain = models.ForeignKey(TaskChain, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    order = models.PositiveIntegerField(help_text="Order of task in the chain (lower numbers run first)")

    def __str__(self):
        return f"{self.chain.name} - {self.task.name} (order: {self.order})"


# Register models with the permission registry when DAB is available
# Temporarily disabled due to DAB content type issues - can be re-enabled once system is stable
# if DAB_AVAILABLE:
#     permission_registry.register(Organization, parent_field_name=None)
#     permission_registry.register(Team)
#     permission_registry.register(Animal, parent_field_name="owner")
#     permission_registry.register(Task, parent_field_name="created_by")
#     permission_registry.register(TaskChain, parent_field_name="created_by")
