"""
Core models for metrics_service.
For full AAP/DAB features, install with: pip install -e ".[dev]"
"""

# Import DAB components - DAB is always available in this environment
from datetime import datetime

from ansible_base.activitystream.models import AuditableModel
from ansible_base.lib.abstract_models import (
    AbstractDABUser,
    AbstractOrganization,
    AbstractTeam,
    CommonModel,
    NamedCommonModel,
)
from ansible_base.lib.utils.models import user_summary_fields
from ansible_base.resource_registry.fields import AnsibleResourceField

# Password handling functions from DAB
from django.contrib.auth.hashers import (
    UNUSABLE_PASSWORD_PREFIX,
    UNUSABLE_PASSWORD_SUFFIX_LENGTH,
    get_hashers_by_algorithm,
    identify_hasher,
    make_password,
)
from django.db import models

from .mixins import AccessControlMixin, UserRelatedMixin


def password_is_hashed(password):
    """
    Returns a boolean of whether password is hashed with loaded algorithms.
    """
    if password is None:
        return False
    try:
        hasher = identify_hasher(password)
    except ValueError:
        # hasher can't be identified or is not loaded
        return False
    return hasher.algorithm in get_hashers_by_algorithm()


def password_is_usable(password):
    """
    Returns True if password is None or wasn't generated by django.contrib.auth.hashers.make_password(None).
    """
    unusable_password_len = len(UNUSABLE_PASSWORD_PREFIX) + UNUSABLE_PASSWORD_SUFFIX_LENGTH

    return password is None or not (
        password.startswith(UNUSABLE_PASSWORD_PREFIX) and len(password) == unusable_password_len
    )


class Organization(AbstractOrganization, AccessControlMixin, UserRelatedMixin):
    """
    Organization model with user and admin management capabilities.

    This model represents an organization that can contain users and admins.
    It inherits from AbstractOrganization for DAB compatibility and includes
    access control functionality through AccessControlMixin.
    """

    class Meta:
        ordering = ["id"]
        permissions = [
            ("member_organization", "User is member of this organization"),
        ]

    resource = AnsibleResourceField(primary_key_field="id")

    # UserRelatedMixin provides users and admins fields
    # Override to customize related_name for organizations
    users = models.ManyToManyField(
        "User",
        related_name="member_of_organizations",
        blank=True,
        help_text="The list of users on this organization",
    )

    admins = models.ManyToManyField(
        "User",
        related_name="admin_of_organizations",
        blank=True,
        help_text="The list of admins for this organization",
    )

    # Example custom field - replace or remove as needed
    extra_field = models.CharField(max_length=100, null=True, blank=True)

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Includes system auditor logic for read-only access to all organizations.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # System administrators can see everything
        if user.is_superuser:
            return queryset

        # System auditors can see all organizations (read-only)
        if hasattr(user, "is_system_auditor") and getattr(user, "is_system_auditor", False):
            return queryset

        # Regular users: filter by organization membership
        # Only show organizations where user is a member or admin
        user_orgs = queryset.filter(models.Q(users=user) | models.Q(admins=user)).distinct()

        return user_orgs

    def __str__(self):
        """
        Return string representation of the organization.

        Returns:
            str: Organization name
        """
        return self.name


class User(AbstractDABUser, CommonModel, AuditableModel, AccessControlMixin):
    """
    Custom User model with enhanced functionality.

    This model extends the AbstractDABUser with additional functionality
    including access control and proper password handling.
    """

    class Meta(AbstractDABUser.Meta):
        ordering = ["id"]

    # Override the groups and user_permissions to avoid conflicts with auth.User
    groups = models.ManyToManyField(
        "auth.Group",
        verbose_name="groups",
        blank=True,
        help_text="The groups this user belongs to.",
        related_name="core_user_set",
        related_query_name="core_user",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        verbose_name="user permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        related_name="core_user_set",
        related_query_name="core_user",
    )

    # System auditor flag
    is_system_auditor = models.BooleanField(
        default=False, help_text="Designates that this user has read-only access to all resources."
    )
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="The organization this user belongs to.",
    )

    resource = AnsibleResourceField(primary_key_field="id")
    activity_stream_excluded_field_names = ["last_login", "password"]

    def save(self, *args, **kwargs):
        """
        Override save to handle password hashing and organization membership.
        """
        # Store the old organization if this is an update
        old_organization = None
        if self.pk:
            try:
                old_user = User.objects.get(pk=self.pk)
                old_organization = old_user.organization
            except User.DoesNotExist:
                pass

        if self.password == "":
            self.password = None

        if password_is_usable(self.password) and not password_is_hashed(self.password):
            self.password = make_password(self.password)

        super().save(*args, **kwargs)

        # Handle organization membership after save
        self._handle_organization_membership(old_organization)

    def _handle_organization_membership(self, old_organization):
        """
        Automatically manage organization membership when user's organization changes.
        """
        # Remove from old organization if it changed
        if old_organization and old_organization != self.organization:
            old_organization.users.remove(self)

        # Add to new organization if one is assigned
        if self.organization and not self.organization.users.filter(id=self.id).exists():
            self.organization.users.add(self)
        # Add user to the organization's users if not already there

    def summary_fields(self):
        """
        Return summary fields for this user.

        Returns:
            dict: Summary fields dictionary
        """
        return user_summary_fields(self)

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Includes system auditor logic for read-only access to all users.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # System administrators can see all users
        if user.is_superuser:
            return queryset

        # System auditors can see all users (read-only)
        if hasattr(user, "is_system_auditor_user") and user.is_system_auditor_user():
            return queryset

        # Regular users: filter by organization relationships
        # Show users in same organizations or teams
        user_organizations = user.member_of_organizations.all()
        user_teams = user.teams.all()

        accessible_users = queryset.filter(
            models.Q(id=user.id)  # Always include self
            | models.Q(member_of_organizations__in=user_organizations)  # Same org members
            | models.Q(teams__in=user_teams)  # Same team members
        ).distinct()

        return accessible_users

    def is_system_administrator(self):
        """
        Check if user has system administrator privileges.
        System administrators have full access to all resources.
        """
        return self.is_superuser

    def is_system_auditor_user(self):
        """
        Check if user has system auditor privileges (read-only access).
        System auditors can view all resources but cannot modify them.
        """
        return self.is_system_auditor

    def can_manage_organization(self, organization):
        """Check if user can manage a specific organization."""
        return self.is_system_administrator() or organization.admins.filter(id=self.id).exists()

    def can_view_organization(self, organization):
        """Check if user can view a specific organization."""
        return (
            self.is_system_administrator()
            or self.is_system_auditor_user()
            or organization.users.filter(id=self.id).exists()
            or organization.admins.filter(id=self.id).exists()
        )

    def can_manage_team(self, team):
        """Check if user can manage a specific team."""
        return (
            self.is_system_administrator()
            or team.admins.filter(id=self.id).exists()
            or self.can_manage_organization(team.organization)
        )

    def __str__(self):
        """
        Return string representation of the user.

        Returns:
            str: Username
        """
        return self.username


class Team(AbstractTeam, AccessControlMixin, UserRelatedMixin):
    """
    Team model with hierarchical organization support.

    This model represents a team within an organization that can contain
    users and admins, with support for team hierarchies.
    """

    class Meta:
        ordering = ["id"]
        abstract = False
        unique_together = [("organization", "name")]
        ordering = ("organization__name", "name")
        permissions = [("member_team", "Has all roles assigned to this team")]

    resource = AnsibleResourceField(primary_key_field="id")

    team_parents = models.ManyToManyField(
        "Team",
        related_name="team_children",
        blank=True,
        help_text="Parent teams for hierarchy support",
    )

    # Override UserRelatedMixin fields to use proper User model and related_name
    users = models.ManyToManyField(
        User,
        related_name="teams",
        blank=True,
        help_text="The list of users on this team",
    )

    admins = models.ManyToManyField(
        User,
        related_name="teams_administered",
        blank=True,
        help_text="The list of admins for this team",
    )

    # Relations to ignore for certain operations
    ignore_relations = []

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Includes system auditor logic for read-only access to all teams.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # System administrators can see all teams
        if user.is_superuser:
            return queryset

        # System auditors can see all teams (read-only)
        if hasattr(user, "is_system_auditor_user") and user.is_system_auditor_user():
            return queryset

        # Regular users: filter by organization and team membership
        user_organizations = user.member_of_organizations.all()

        accessible_teams = queryset.filter(
            models.Q(organization__in=user_organizations)  # Teams in user's orgs
            | models.Q(users=user)  # Teams user is member of
            | models.Q(admins=user)  # Teams user administers
        ).distinct()

        return accessible_teams

    def __str__(self):
        """
        Return string representation of the team.

        Returns:
            str: Organization name and team name
        """
        return f"{self.organization.name} - {self.name}"


class Task(NamedCommonModel, AuditableModel):
    """
    Database model for scheduled tasks with enhanced tracking capabilities.

    This model provides comprehensive task scheduling and execution tracking
    with support for dependencies, recurring tasks, and detailed status monitoring.
    """

    class Meta:
        ordering = ["id"]
        permissions = [("can_execute_task", "Can execute task")]

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("running", "Running"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("cancelled", "Cancelled"),
        ("waiting_for_dependencies", "Waiting for Dependencies"),
    ]

    PRIORITY_CHOICES = [
        (1, "Low"),
        (2, "Normal"),
        (3, "High"),
        (4, "Critical"),
    ]

    # Task identification and metadata
    function_name = models.CharField(
        max_length=255, help_text="Name of the function to execute (must match TASK_FUNCTIONS)"
    )

    task_data = models.JSONField(default=dict, help_text="JSON data to pass to the task function")

    # Scheduling information
    scheduled_time = models.DateTimeField(
        null=True, blank=True, help_text="When the task should be executed (null for immediate execution)"
    )

    cron_expression = models.CharField(
        max_length=100, null=True, blank=True, help_text="Cron expression for recurring tasks (e.g., '0 2 * * *')"
    )

    is_recurring = models.BooleanField(
        default=False, help_text="Whether this task should repeat based on cron_expression"
    )

    # Execution tracking
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default="pending")

    priority = models.IntegerField(
        choices=PRIORITY_CHOICES, default=2, help_text="Task priority (higher numbers = higher priority)"
    )

    attempts = models.PositiveIntegerField(default=0, help_text="Number of execution attempts")

    max_attempts = models.PositiveIntegerField(default=3, help_text="Maximum number of retry attempts")

    timeout_seconds = models.PositiveIntegerField(default=3600, help_text="Task timeout in seconds")

    # Execution results (inherited from StatusTrackingMixin)
    result_data = models.JSONField(default=dict, blank=True, help_text="JSON result data from task execution")

    # Ownership and organization
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_tasks",
        help_text="User who created this task",
    )

    def __str__(self):
        """
        Return string representation of the task.

        Returns:
            str: Task name, function name, and status
        """
        return f"{self.name} ({self.function_name}) - {self.get_status_display()}"

    def is_ready_to_run(self) -> bool:
        """
        Check if task is ready to be executed.

        Returns:
            bool: True if task is ready to run, False otherwise
        """
        from django.utils import timezone

        if self.status != "pending":
            return False

        # Check if dependencies are completed
        if self.dependencies.filter(
            prerequisite_task__status__in=["pending", "running", "waiting_for_dependencies"]
        ).exists():
            return False

        # Check if scheduled time has passed
        return not (self.scheduled_time and self.scheduled_time > timezone.now())

    def can_retry(self) -> bool:
        """
        Check if task can be retried.
        Returns:
            bool: True if task can be retried, False otherwise
        """
        return self.attempts < self.max_attempts and self.status == "failed"

    def get_next_run_time(self) -> datetime | None:
        """
        Calculate next run time for recurring tasks.

        Returns:
            datetime or None: Next run time for recurring tasks, None if not recurring
        """
        if not self.is_recurring or not self.cron_expression:
            return None

        try:
            from croniter import croniter
            from django.utils import timezone

            cron = croniter(self.cron_expression, timezone.now())
            return cron.get_next(datetime)
        except ImportError:
            # croniter not available, return None
            return None
        except Exception:
            # Invalid cron expression
            return None


class TaskDependency(CommonModel):
    """
    Model to define task dependencies for chaining.

    This model allows creating dependencies between tasks to ensure
    proper execution order in complex workflows.
    """

    class Meta:
        unique_together = ["dependent_task", "prerequisite_task"]
        verbose_name_plural = "Task Dependencies"

    dependent_task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name="dependencies", help_text="Task that depends on another task"
    )

    prerequisite_task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name="dependents",
        help_text="Task that must complete before dependent_task can run",
    )

    required_status = models.CharField(
        max_length=30,
        choices=Task.STATUS_CHOICES,
        default="completed",
        help_text="Required status of prerequisite task",
    )

    def __str__(self):
        """
        Return string representation of the task dependency.

        Returns:
            str: Dependency relationship description
        """
        return f"{self.dependent_task.name} depends on {self.prerequisite_task.name}"


class TaskExecution(CommonModel, AuditableModel):
    """
    Model to track individual task executions for history and debugging.

    This model provides detailed tracking of task execution attempts,
    including timing, results, and error information.
    """

    class Meta:
        ordering = ["-started_at"]

    task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name="executions", help_text="The task that was executed"
    )

    status = models.CharField(max_length=30, choices=Task.STATUS_CHOICES)

    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    worker_id = models.CharField(
        max_length=100, null=True, blank=True, help_text="ID of the worker that executed the task"
    )

    result_data = models.JSONField(default=dict, blank=True, help_text="JSON result data from this execution")

    error_message = models.TextField(blank=True, help_text="Error message if execution failed")

    execution_time_seconds = models.FloatField(
        null=True, blank=True, help_text="Time taken to execute the task in seconds"
    )

    def __str__(self):
        """
        Return string representation of the task execution.

        Returns:
            str: Task name and execution timestamp
        """
        return f"{self.task.name} execution at {self.started_at}"

    def save(self, *args, **kwargs):
        """
        Override save to calculate execution time automatically.

        Args:
            *args: Positional arguments
            **kwargs: Keyword arguments

        Returns:
            None
        """
        # Calculate execution time if completed
        if self.completed_at and self.started_at:
            self.execution_time_seconds = (self.completed_at - self.started_at).total_seconds()
        super().save(*args, **kwargs)


class TaskChain(NamedCommonModel, AuditableModel, AccessControlMixin):
    """
    Model to define named task chains for complex workflows.

    This model allows grouping tasks into ordered chains for executing
    complex workflows with specific sequencing requirements.
    """

    class Meta:
        ordering = ["id"]

    tasks = models.ManyToManyField(
        Task, through="TaskChainMembership", related_name="chains", help_text="Tasks in this chain"
    )

    is_active = models.BooleanField(default=True, help_text="Whether this chain is active")

    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="created_chains"
    )

    def __str__(self):
        """
        Return string representation of the task chain.

        Returns:
            str: Task chain name
        """
        return self.name


class TaskChainMembership(CommonModel):
    """
    Through model for TaskChain to Task relationship with ordering.

    This model defines the order and relationship between tasks within
    a task chain, allowing for proper sequencing of workflow execution.
    """

    class Meta:
        unique_together = ["chain", "task"]
        ordering = ["order"]

    chain = models.ForeignKey(TaskChain, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    order = models.PositiveIntegerField(help_text="Order of task in the chain (lower numbers run first)")

    def __str__(self):
        """
        Return string representation of the task chain membership.

        Returns:
            str: Chain name, task name, and order
        """
        return f"{self.chain.name} - {self.task.name} (order: {self.order})"
