"""
Core models for metrics_service.
For full AAP/DAB features, install with: pip install -e ".[dev]"
"""

from typing import Any

from django.contrib.auth.models import AbstractUser
from django.db import models

from .mixins import AccessControlMixin, UserRelatedMixin

# Basic models for immediate setup
# For full AAP features, replace with DAB abstract models when ready
try:
    from ansible_base.activitystream.models import AuditableModel
    from ansible_base.lib.abstract_models import (
        AbstractDABUser,
        AbstractOrganization,
        AbstractTeam,
        CommonModel,
        NamedCommonModel,
    )
    from ansible_base.lib.utils.models import user_summary_fields
    from ansible_base.resource_registry.fields import AnsibleResourceField

    DAB_AVAILABLE = True
except ImportError:
    # Provide simple alternatives for immediate setup
    DAB_AVAILABLE = False

    # Simple base classes when DAB is not available
    class CommonModel(models.Model):
        created: models.DateTimeField = models.DateTimeField(auto_now_add=True)
        modified: models.DateTimeField = models.DateTimeField(auto_now=True)

        class Meta:
            abstract = True

    class NamedCommonModel(CommonModel):
        name: models.CharField = models.CharField(max_length=512)
        description: models.TextField = models.TextField(blank=True, default="")

        class Meta:
            abstract = True

    class AuditableModel(models.Model):
        class Meta:
            abstract = True

    class AbstractDABUser(AbstractUser):
        class Meta:
            abstract = True

    class AbstractOrganization(NamedCommonModel):
        class Meta:
            abstract = True

    class AbstractTeam(NamedCommonModel):
        organization: models.ForeignKey = models.ForeignKey("Organization", on_delete=models.CASCADE)

        class Meta:
            abstract = True


# Password handling functions - only available when DAB is enabled
if DAB_AVAILABLE:
    from django.contrib.auth.hashers import (
        UNUSABLE_PASSWORD_PREFIX,
        UNUSABLE_PASSWORD_SUFFIX_LENGTH,
        get_hashers_by_algorithm,
        identify_hasher,
        make_password,
    )

    def password_is_hashed(password):
        """
        Returns a boolean of whether password is hashed with loaded algorithms.
        """
        if password is None:
            return False
        try:
            hasher = identify_hasher(password)
        except ValueError:
            # hasher can't be identified or is not loaded
            return False
        return hasher.algorithm in get_hashers_by_algorithm()

    def password_is_usable(password):
        """
        Returns True if password is None or wasn't generated by django.contrib.auth.hashers.make_password(None).
        """
        unusable_password_len = len(UNUSABLE_PASSWORD_PREFIX) + UNUSABLE_PASSWORD_SUFFIX_LENGTH

        return password is None or not (
            password.startswith(UNUSABLE_PASSWORD_PREFIX) and len(password) == unusable_password_len
        )


class Organization(AbstractOrganization, AccessControlMixin, UserRelatedMixin):
    """
    Organization model with user and admin management capabilities.

    This model represents an organization that can contain users and admins.
    It inherits from AbstractOrganization for DAB compatibility and includes
    access control functionality through AccessControlMixin.
    """

    class Meta:
        ordering = ["id"]
        permissions = [
            ("member_organization", "User is member of this organization"),
        ]

    if DAB_AVAILABLE:
        resource = AnsibleResourceField(primary_key_field="id")

    # UserRelatedMixin provides users and admins fields
    # Override to customize related_name for organizations
    users: models.ManyToManyField = models.ManyToManyField(
        "User",
        related_name="member_of_organizations",
        blank=True,
        help_text="The list of users on this organization",
    )

    admins: models.ManyToManyField = models.ManyToManyField(
        "User",
        related_name="admin_of_organizations",
        blank=True,
        help_text="The list of admins for this organization",
    )

    # Example custom field - replace or remove as needed
    extra_field: models.CharField = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        """
        Return string representation of the organization.

        Returns:
            str: Organization name
        """
        return self.name


class User(AbstractDABUser, CommonModel, AuditableModel, AccessControlMixin):
    """
    Custom User model with enhanced functionality.

    This model extends the AbstractDABUser with additional functionality
    including access control and proper password handling.
    """

    class Meta(AbstractDABUser.Meta):
        ordering = ["id"]

    # Override the groups and user_permissions to avoid conflicts with auth.User
    groups: models.ManyToManyField = models.ManyToManyField(
        "auth.Group",
        verbose_name="groups",
        blank=True,
        help_text="The groups this user belongs to.",
        related_name="core_user_set",
        related_query_name="core_user",
    )
    user_permissions: models.ManyToManyField = models.ManyToManyField(
        "auth.Permission",
        verbose_name="user permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        related_name="core_user_set",
        related_query_name="core_user",
    )

    if DAB_AVAILABLE:
        resource = AnsibleResourceField(primary_key_field="id")
        activity_stream_excluded_field_names = ["last_login", "password"]

    def save(self, *args, **kwargs):
        """
        Override save to handle password hashing when DAB is available.

        Args:
            *args: Positional arguments
            **kwargs: Keyword arguments

        Returns:
            None
        """
        if DAB_AVAILABLE:
            if self.password == "":
                self.password = None

            if password_is_usable(self.password) and not password_is_hashed(self.password):
                self.password = make_password(self.password)
        super().save(*args, **kwargs)

    def summary_fields(self) -> dict[str, Any]:
        """
        Return summary fields for this user.

        Returns:
            dict: Summary fields dictionary
        """
        if DAB_AVAILABLE:
            return user_summary_fields(self)
        return {}

    def __str__(self):
        """
        Return string representation of the user.

        Returns:
            str: Username
        """
        return self.username


class Team(AbstractTeam, AccessControlMixin, UserRelatedMixin):
    """
    Team model with hierarchical organization support.

    This model represents a team within an organization that can contain
    users and admins, with support for team hierarchies.
    """

    class Meta:
        ordering = ["id"]
        abstract = False
        unique_together = [("organization", "name")]
        ordering = ("organization__name", "name")
        permissions = [("member_team", "Has all roles assigned to this team")]

    if DAB_AVAILABLE:
        resource = AnsibleResourceField(primary_key_field="id")

    team_parents: models.ManyToManyField = models.ManyToManyField(
        "Team",
        related_name="team_children",
        blank=True,
        help_text="Parent teams for hierarchy support",
    )

    # Override UserRelatedMixin fields to use proper User model and related_name
    users: models.ManyToManyField = models.ManyToManyField(
        User,
        related_name="teams",
        blank=True,
        help_text="The list of users on this team",
    )

    admins: models.ManyToManyField = models.ManyToManyField(
        User,
        related_name="teams_administered",
        blank=True,
        help_text="The list of admins for this team",
    )

    # Relations to ignore for certain operations
    ignore_relations: list[str] = []

    def __str__(self):
        """
        Return string representation of the team.

        Returns:
            str: Organization name and team name
        """
        return f"{self.organization.name} - {self.name}"
