# Generated by Django 5.2.17 on 2026-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticspayload",
            name="cluster_id",
            field=models.CharField(
                blank=True,
                help_text="Controller installation UUID (INSTALL_UUID) read from the AWX database, if available.",
                max_length=64,
                null=True,
            ),
        ),
    ]
