# Generated by Django 5.2.7 on 2026-09-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsCollectionClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("claim_key", models.CharField(max_length=64, unique=True)),
                ("collector", models.CharField(max_length=128)),
                ("source", models.CharField(default="local", max_length=64)),
                ("since", models.DateTimeField(blank=True, null=True)),
                ("until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "payload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_claims",
                        to="analytics.analyticspayload",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_claims",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Collection Claim",
                "verbose_name_plural": "Analytics Collection Claims",
                "indexes": [
                    models.Index(fields=["collector", "source", "status"], name="analytics_a_collect_8a1d67_idx"),
                    models.Index(fields=["modified"], name="analytics_a_modifie_91a77c_idx"),
                ],
            },
        ),
    ]
