# Generated by Django 5.2.17 on 2026-09-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analyticscollectionclaim_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticscollectionclaim',
            new_name='analytics_a_collect_bae55f_idx',
            old_name='analytics_a_collect_8a1d67_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticscollectionclaim',
            new_name='analytics_a_modifie_7b9325_idx',
            old_name='analytics_a_modifie_91a77c_idx',
        ),
    ]
